# Project: SimpleGame
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Fight.o Items.o
LINKOBJ  = main.o Fight.o Items.o
LIBS     = -L"G:/Programs/Dev-Cpp/MinGW64/lib" -L"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"G:/Programs/Dev-Cpp/MinGW64/include" -I"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"G:/Programs/Dev-Cpp/MinGW64/include" -I"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = SimpleGame.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Fight.o: Fight.cpp
	$(CPP) -c Fight.cpp -o Fight.o $(CXXFLAGS)

Items.o: Items.cpp
	$(CPP) -c Items.cpp -o Items.o $(CXXFLAGS)
